# Generated by Django 5.0.14 on 2026-01-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_product_created_at_product_slug_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="is_paid",
        ),
        migrations.RemoveField(
            model_name="order",
            name="total_amount",
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("COD", "Cash on Delivery"), ("ONLINE", "Online Payment")],
                default="COD",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLACED", "Placed"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PLACED",
                max_length=20,
            ),
        ),
    ]
